name: yiclass
description: A Flutter class schedule application

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5        
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  file_picker: ^10.1.2
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
