name: yiclass
description: 一个课表管理工具，支持多种课程表格式导入，支持多种平台。

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  file_picker: ^10.1.2
  webview_flutter: ^4.11.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# 设置应用图标（桌面图标）
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

# 设置启动页动画
flutter_native_splash:
  color: "#ffffff"                # 启动页背景色
  image: assets/icon/app_logo.png # 居中 Logo 图像
  android: true
  ios: true
  web: false
